### PR TITLE
Build Optimization and Fix script warning

### LINKED ISSUE #1447: `--state-cache-size` was deprecated. Please switch to `--trie-cache-size`.
`make start-frequency` generates a warning that we should resolve:

```
Bootnode: /ip4/127.0.0.1/tcp/30336/p2p/12D3KooWKpaJZbNymrZmKG6BNNDC58z8p9YKDXfZtyhEjktgtph4
+ ./target/release/frequency --chain=frequency-local --alice --base-path=/tmp/frequency/parachain/2000/data --wasm-execution=compiled --execution=wasm --force-authoring --port 30333 --rpc-port 9933 --ws-port 9944 --rpc-external --rpc-cors all --ws-external --rpc-methods=Unsafe --state-cache-size 0 -- --wasm-execution=compiled --execution=wasm --chain=./resources/rococo-local.json --bootnodes=/ip4/127.0.0.1/tcp/30335/p2p/12D3KooWDLpRT9KFo6pKdkmdQQt599tmqVYpoeiHemY32Gf4RUpp --bootnodes=/ip4/127.0.0.1/tcp/30336/p2p/12D3KooWKpaJZbNymrZmKG6BNNDC58z8p9YKDXfZtyhEjktgtph4
`--state-cache-size` was deprecated. Please switch to `--trie-cache-size`.
```

## Resolution
Remove `state-cache-size` from `scripts/init.sh`

### LINKED ISSUE #1499: Upgrade subwasm to 0.19.1
New version of subwasm is out and it has some nice small improvements.

- [ ] ci
- [ ] scripts

### PR DESCRIPTION
**Pull request by wilwade**
# Goal
The goal of this PR is a few different cleanups:

- Upgrade subwasm to 0.19.1
- Add security email to the Readme
- Fix trie-cache-size error
- fix build speed issue in handles-util/build.rs

Closes #1447
Closes #1499 

# How to test
- Build issue: You can now run `make build` and then `make build` and the second one will not redo stuff
- Trie-cache-size: `make start-frequency` will not show the warning

### CODE REVIEW

File: pallets/handles/src/handles-utils/build.rs [hunk 1]
```diff
@@ -14,6 +14,10 @@ fn allowed_char(c: char) -> bool {
 
 #[allow(clippy::unwrap_used)]
 fn main() {
+	println!("cargo:rerun-if-changed=build.rs");
+	println!("cargo:rerun-if-changed=src/data/confusable_characters.txt");
+	println!("cargo:rerun-if-changed=constants.rs");
+
```
Comment (wilwade) [inline pallets/handles/src/handles-utils/build.rs:20]: This should be at the top and `src/data` not `data` was causing it to run everytime.

**Review by JoeCap08055 — APPROVED** [review]
