### PR TITLE
Batched Capacity Transactions

### LINKED ISSUE #1276: [Handles] batch capacity calls
As a network, Frequency would like to batch create handles tx so that I dont need to make multiple calls for a single action. 

## Possible Solutions
1. `batch(pay_with_capacity(capCall1), pay_with_capacity(capCall2),...)` FAIL: Requires tokens
2. `pay_with_capacity(batch_all(capCall1, capCall2, ...))` Possible Good
3. `pay_with_capacity_batch_all(capCall1, capCall2, ...))` Possible Good
4. `pay_with_capacity_batch_all(listOfCalls) -> {batch_all(listOfCalls)}` Chosen!

## Suggested Impl for Chosen 4

- [x] Create new extrinsic `pay_with_capacity_batch_all(vecOfCapacityCalls)`
- [x] `pay_with_capacity_batch_all` should check that `vecOfCapacityCalls` has length < MAX_CAPACITY_BATCH_LENGTH (start at `2`)
- [x] `pay_with_capacity_batch_all` then internally creates the extrinsic call and calls `utility.batch_all(vecOfCapacityCalls)`
    - This is what will return the "block" weight for the call instead of the "capacity" weight
- [x] Update the `SignedExtension for ChargeFrqTransactionPayment` sub call `withdraw_fee` to support the new `pay_with_capacity_batch_all` and throw an error if ANY sub call is NOT an approved capacity call.
- [ ] Copy a lot of weights from the batch_all in extrinsic

Notes: `withdraw_capacity_fee` ALSO checks that the calls is a capacity allowed call

### `withdraw_fee` Notes
```
Some(Call::pay_with_capacity { call }) => self.withdraw_capacity_fee(who, call, len),
Some(Call::pay_with_capacity_batch_all { calls }) => calls.iter().reduce(|call, sum| sum.saturating_add(self.withdraw_capacity_fee(who, call, len).ok_or(CallIsNotCapacityEligible)),
```

### PR DESCRIPTION
**Pull request by johnmela**
# Goal
Add the ability to pay for a batch of Capacity transactions.             

The `pay_with_capacity_batch_all` extrinsic was added to the `frequency-tx-payment` pallet.

Closes #1276

### CODE REVIEW

File: common/primitives/src/node.rs [hunk 1]
```diff
@@ -59,3 +59,9 @@ pub trait ProposalProvider<AccountId, Proposal> {
 	#[cfg(any(feature = "runtime-benchmarks", feature = "test"))]
 	fn proposal_count() -> u32;
 }
+
+/// The provider for interfacing into the Utility pallet.
+pub trait UtilityProvider<Origin, RuntimeCall> {
```
Comment (enddynayn) [inline common/primitives/src/node.rs:64]: Nice! 💯

File: pallets/frequency-tx-payment/src/lib.rs [hunk 2]
```diff
@@ -324,6 +369,29 @@ where
 		Ok((fee.into(), InitialPayment::Capacity))
 	}
 
+	/// Withdraws transaction fee paid Capacity using a key associated to an MSA of a batch of calls.
+	fn withdraw_capacity_fee_batch(
```
Comment (johnmela) [inline pallets/frequency-tx-payment/src/lib.rs:373]: We separated `withdraw_capacity_fee_batch` into a separate function to get `pay_with_capacity_batch_all` working. Combining functionality so that `withdraw_capacity_fee` can handle both `pay_with_capacity` and `pay_with_capacity_batch_all` extrinsic calls would be a nice to have

**Review by wilwade — COMMENTED** [review]
One or two comments. Only the DB one is blocking

File: pallets/frequency-tx-payment/src/lib.rs [hunk 3]
```diff
@@ -299,10 +343,11 @@ where
 	) -> Result<(BalanceOf<T>, InitialPayment<T>), TransactionValidityError> {
 		match call.is_sub_type() {
 			Some(Call::pay_with_capacity { call }) => self.withdraw_capacity_fee(who, call, len),
```
[the remark this answers is not in the document]
Comment (johnmela) [reply pallets/frequency-tx-payment/src/lib.rs:343]: There were some type mismatches when expanding the vec![] macro. The fix might be simple but as per our discussion, I recommend we follow up after the merge

**Review by wilwade — APPROVED** [review]
LGTM!

File: pallets/frequency-tx-payment/src/lib.rs [hunk 4]
```diff
@@ -168,12 +171,24 @@ pub mod pallet {
 
 		/// Charge Capacity for transaction payments.
 		type OnChargeCapacityTransaction: OnChargeCapacityTransaction<Self>;
+
+		/// The maxmimum number of capacity calls that can be batched together.
+		#[pallet::constant]
+		type MaximumCapacityBatchLength: Get<u8>;
+
+		type BatchAllProvider: UtilityProvider<OriginFor<Self>, <Self as Config>::RuntimeCall>;
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/lib.rs:179]: I thin you can drop the All from here.

File: pallets/frequency-tx-payment/src/lib.rs [hunk 5]
```diff
@@ -205,6 +219,33 @@ pub mod pallet {
...
+		let dispatch_weight = dispatch_infos.iter()
+				.map(|di| di.weight)
+				.fold(Weight::zero(), |total: Weight, weight: Weight| total.saturating_add(weight));
+
+		let capacity_overhead = T::DbWeight::get().reads(2)
+			.saturating_add(
+				T::DbWeight::get().writes(1)
+			);
+		let total = capacity_overhead.saturating_add(dispatch_weight);
+		(< T as Config >::WeightInfo::pay_with_capacity().saturating_add(total), DispatchClass::Normal)
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/lib.rs:235]: I just wanted to remind you that we added this quickly to have something. I recommend adding the benchmarks and running them.

File: pallets/frequency-tx-payment/src/lib.rs (hunk 4 above)
Comment (shannonwells) [reply pallets/frequency-tx-payment/src/lib.rs:179]: Agree

File: pallets/frequency-tx-payment/src/mock.rs [hunk 6]
```diff
@@ -237,13 +239,30 @@ impl GetStableWeight<RuntimeCall, Weight> for TestCapacityCalls {
...
+}
+
 impl Config for Test {
 	type RuntimeEvent = RuntimeEvent;
 	type RuntimeCall = RuntimeCall;
 	type Capacity = Capacity;
 	type WeightInfo = ();
 	type CapacityCalls = TestCapacityCalls;
 	type OnChargeCapacityTransaction = payment::CapacityAdapter<Balances, Msa>;
+	type MaximumCapacityBatchLength = MaximumCapacityBatchLength;
```
[the remark this answers is not in the document]
Comment (enddynayn) [reply pallets/frequency-tx-payment/src/mock.rs:264]: Actually, I take that back.

File: pallets/frequency-tx-payment/src/lib.rs (hunk 5 above)
Comment (johnmela) [reply pallets/frequency-tx-payment/src/lib.rs:235]: Thank you, great catch

File: pallets/frequency-tx-payment/src/lib.rs [hunk 7]
```diff
@@ -299,10 +341,11 @@ where
 	) -> Result<(BalanceOf<T>, InitialPayment<T>), TransactionValidityError> {
 		match call.is_sub_type() {
 			Some(Call::pay_with_capacity { call }) => self.withdraw_capacity_fee(who, call, len),
+			Some(Call::pay_with_capacity_batch_all { calls }) =>
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/lib.rs:344]: I think we then unbox the value using the dereference operator * on call (*call). We also would need to clone it.
```
Some(Call::pay_with_capacity { call }) => self.withdraw_capacity(who, &[*call.clone()], len);
or
Some(Call::pay_with_capacity { call }) => self.withdraw_capacity(who, &vec![*call.clone()], len);
```

File: pallets/frequency-tx-payment/src/tests.rs [hunk 8]
```diff
@@ -664,3 +698,70 @@ fn compute_capacity_fee_successful() {
...
+			let who = 1u64;
+
+			assert_noop!(
+				FrequencyTxPayment::pay_with_capacity_batch_all(
+					RuntimeOrigin::signed(who),
+					too_many_calls
+				),
+				Error::<Test>::BatchedCallAmountExceedMaximum
+			);
+		});
```
Comment (shannonwells) [inline pallets/frequency-tx-payment/src/tests.rs:725]: I'd like to see a token balance check here too as in the following test.

File: pallets/frequency-tx-payment/src/lib.rs [hunk 9]
```diff
@@ -205,6 +219,33 @@ pub mod pallet {
 
 			call.dispatch(origin)
 		}
+
+		#[pallet::call_index(1)]
+		#[pallet::weight({
+		let dispatch_infos = calls.iter().map(|call| call.get_dispatch_info()).collect::<Vec<_>>();
+		let dispatch_weight = dispatch_infos.iter()
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/lib.rs:226]: I think we can create an overhead_weight function since the computation is done in both `pay_with_capacity` and `pay_with_capacity_batch_all` and we leave that big comment at the top of it.

```
/// Dispatch the given call as a sub_type of pay_with_capacity. Calls dispatched in this
		/// fashion, if allowed, will pay with Capacity
		// The weight calculation is a temporary adjustment because overhead benchmarks do not account
		// for capacity calls.  We count reads and writes for a pay_with_capacity call,
		// then subtract one of each for regular transactions since overhead benchmarks account for these.
		//	 Storage: Msa PublicKeyToMsaId (r:1)
		//   Storage: Capacity CapacityLedger(r:1, w:2)
		//   Storage: Capacity CurrentEpoch(r:1) ? maybe cached in on_initialize
		//   Storage: System Account(r:1)
		//   Total (r: 4-1=3, w: 2-1=1)
```

File: pallets/frequency-tx-payment/src/tests.rs [hunk 10]
```diff
@@ -664,3 +698,70 @@ fn compute_capacity_fee_successful() {
...
+
+			let calls_to_batch =
+				vec![successful_balance_transfer_call, balance_transfer_call_insufficient_funds];
+
+			let result = FrequencyTxPayment::pay_with_capacity_batch_all(
+				RuntimeOrigin::signed(origin),
+				calls_to_batch,
+			);
+
+			assert!(match result {
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/tests.rs:754]: what whats the Error you get when you fail?

assert_eq!(
  FrequencyTxPayment::pay_with_capacity_batch_all(
				RuntimeOrigin::signed(origin),
				calls_to_batch,
			),
			Err(DispatchErrorWithPostInfo {
				error: pallet_utility::<T>::Error::<Test>::SomeError,
				post_info: PostDispatchInfo {
					actual_weight: Some(....),
					pays_fee: Default::default(),
				},
			})
	);

Comment (enddynayn) [reply pallets/frequency-tx-payment/src/tests.rs:754]: Ahh, I think it might be the error from BalancesCall.

File: pallets/frequency-tx-payment/src/tests.rs [hunk 11]
```diff
@@ -664,3 +698,70 @@ fn compute_capacity_fee_successful() {
...
+				_ => {
+					false
+				},
+			});
+
+			let token_balance_after_call = Balances::free_balance(origin);
+
+			assert_eq!(token_balance_before_call, token_balance_after_call);
+		});
+}
```
Comment (enddynayn) [inline pallets/frequency-tx-payment/src/tests.rs:767]: Can you please add a couple of test for the extrinsic pay_with_capacity_batch_all? One Happy path and the other for the error `BatchedCallAmountExceedMaximum`?

File: pallets/frequency-tx-payment/src/lib.rs [hunk 12]
```diff
@@ -168,12 +171,24 @@ pub mod pallet {
...
 	}
 
 	#[pallet::event]
 	#[pallet::generate_deposit(pub (super) fn deposit_event)]
 	pub enum Event<T: Config> {}
 
+	#[pallet::error]
+	pub enum Error<T> {
+		/// The maximum amount of requested batched calls was exceeded
+		BatchedCallAmountExceedMaximum,
```
[the remark this answers is not in the document]
Comment (johnmela) [reply pallets/frequency-tx-payment/src/lib.rs:189]: Good catch, thank you. I'm partial to `BatchedCallAmountExceedsMaximum` because it states why there are too many batched calls, there is an allowed max

File: runtime/frequency/src/lib.rs [hunk 13]
```diff
@@ -112,6 +113,14 @@ impl ProposalProvider<AccountId, RuntimeCall> for CouncilProposalProvider {
 	}
 }
 
+pub struct CapacityBatchProvider;
+
+impl UtilityProvider<RuntimeOrigin, RuntimeCall> for CapacityBatchProvider {
+	fn batch_all(origin: RuntimeOrigin, calls: Vec<RuntimeCall>) -> DispatchResultWithPostInfo {
```
[the remark this answers is not in the document]
Comment (johnmela) [reply runtime/frequency/src/lib.rs:119]: We retained `batch_all` in the naming because this function is serving as a passthrough, wrapping the utility pallet's `batch_all` extrinsic function. I _think_ their rationale is that `pallet_utility::batch` is not atomic whereas `pallet_utility::batch_all` is

File: runtime/common/src/constants.rs [hunk 14]
```diff
@@ -253,6 +253,12 @@ parameter_types! {
 }
 // -end- Transaction Payment Pallet ---
 
+// --- Frequency Transaction Payment Pallet ---
+parameter_types! {
+	pub const MaximumCapacityBatchLength: u8 = 2;
```
[the remark this answers is not in the document]
Comment (johnmela) [reply runtime/common/src/constants.rs:258]: I chose two as a starting point for safety.
The very specific use case that we wish to support is to be able to create an MSA and a handle in one transaction. My concern is abuse potential. What will effects of very batches have on the transaction queue or the chain overall?

It should be fairly simple to bump this as needed? With testing

File: pallets/frequency-tx-payment/src/tests.rs [hunk 15]
```diff
@@ -263,6 +263,40 @@ fn pay_with_capacity_returns_weight_of_child_call() {
...
+						value: 100,
+					})],
+				});
+
+			let info = DispatchInfo { weight: Weight::from_ref_time(5), ..Default::default() };
+			let len = 10;
+
+			// fee = base_weight(5)
+			//   + extrinsic_weight(11) * WeightToFee(1)
+			//   + TransactionByteFee(1)* len(10) = 20
```
[the remark this answers is not in the document]
Comment (johnmela) [reply pallets/frequency-tx-payment/src/tests.rs:291]: I think the comment is wrong

File: pallets/frequency-tx-payment/src/tests.rs (hunk 10 above)
Comment (johnmela) [reply pallets/frequency-tx-payment/src/tests.rs:754]: It is the `InsufficientBalance` error, however it is returned buried in the `DispatchErrorWithPostInfo`

Comment (johnmela) [reply pallets/frequency-tx-payment/src/tests.rs:754]: Maybe we can make it more specific later if necessary? I wanted to be able to capture the fact that the batch failed and that the state of the origin's balance has not change

File: pallets/frequency-tx-payment/src/tests.rs (hunk 11 above)
Comment (johnmela) [reply pallets/frequency-tx-payment/src/tests.rs:804]: Transaction amount maximum  is above this one,
Added the happy path test

**Review by enddynayn — APPROVED** [review]
👍 Fanstastic!
