### PR TITLE
Fix manual/interval sealing to work without empty blocks

### LINKED ISSUE #1537: Fix manual/interval sealing to work without empty blocks
Frequency should be able to seal blocks with `createEmpty=false` and `finalize=false`.  This is a bug in the current manual sealing implementation but is important for interval sealing so that developers don't have to look at empty blocks.

image

### PR DESCRIPTION
**Pull request by rlaferla**
# Goal
The goal of this PR is to fix manual/interval sealing to work without empty blocks.

Closes #1537

Testing:

`./target/debug/frequency --dev --sealing=interval --sealing-create-empty-blocks`
and
`./target/debug/frequency --dev --sealing=interval`

```
Usage:
      --sealing-create-empty-blocks
          Create empty blocks in interval sealing modes
```

2023-05-22 19:49:35 Accepting new connection 1/100
2023-05-22 19:49:38 ⏳ Interval timer triggered    
2023-05-22 19:49:39 💤 Idle (0 peers), best: #0 (0x53a1…1eb8), finalized #0 (0x53a1…1eb8), ⬇ 0 ⬆ 0    
2023-05-22 19:49:44 💤 Idle (0 peers), best: #0 (0x53a1…1eb8), finalized #0 (0x53a1…1eb8), ⬇ 0 ⬆ 0    
2023-05-22 19:49:49 💤 Idle (0 peers), best: #0 (0x53a1…1eb8), finalized #0 (0x53a1…1eb8), ⬇ 0 ⬆ 0    
2023-05-22 19:49:50 ⏳ Interval timer triggered    
2023-05-22 19:49:54 💤 Idle (0 peers), best: #0 (0x53a1…1eb8), finalized #0 (0x53a1…1eb8), ⬇ 0 ⬆ 0    
2023-05-22 19:49:59 💤 Idle (0 peers), best: #0 (0x53a1…1eb8), finalized #0 (0x53a1…1eb8), ⬇ 0 ⬆ 0    
2023-05-22 19:50:02 ⏳ Interval timer triggered

### CODE REVIEW

**Review by mattheworris — APPROVED** [review]
Code looks good, nice catch!

File: node/cli/src/cli.rs [hunk 1]
```diff
@@ -100,6 +100,11 @@ pub struct Cli {
 	#[cfg(feature = "frequency-no-relay")]
 	#[clap(long, help = "The interval in seconds", default_value = "12", value_name = "SECONDS")]
 	pub sealing_interval: NonZeroU16,
+
+	/// Whether to create empty blocks in manual and interval sealing modes.
+	#[cfg(feature = "frequency-no-relay")]
+	#[clap(long, help = "Create empty blocks in interval sealing modes", default_value = "false")]
```
Comment (wilwade) [inline node/cli/src/cli.rs:106]: So we want to have the default true or false? I was imagining true and I guess that would mean inverting the flag name. Thoughts?

File: node/service/src/block_sealing.rs [hunk 2]
```diff
@@ -115,7 +111,7 @@ pub fn frequency_dev_sealing(
 					Poll::Ready(_instant) => {
 						let engine_cmd =
 							sc_consensus_manual_seal::rpc::EngineCommand::SealNewBlock {
-								create_empty: true,
+								create_empty: sealing_create_empty_blocks,
```
Comment (wilwade) [inline node/service/src/block_sealing.rs:114]: Hmm... This logs an error every interval-seconds. I wonder if we need to do the check outside of this to prevent the error. Thoughts?

```ERROR tokio-runtime-worker sc_consensus_manual_seal::rpc: Instant Seal encountered an error: Transaction pool is empty, set create_empty to true, if you want to create empty blocks```

**Review by wilwade — COMMENTED** [review]
Two questions, one about default and one about errors.

That said, all works!
- With flag: ✅ 
- Without flag: ✅

File: node/cli/src/cli.rs (hunk 1 above)
Comment (rlaferla) [reply node/cli/src/cli.rs:106]: No empty blocks seems more useful. Hence, the default of false. What would be the rationale for having empty blocks?

File: node/service/src/block_sealing.rs (hunk 2 above)
Comment (rlaferla) [reply node/service/src/block_sealing.rs:114]: I had tried that but it was before I had found and fixed the underlying issue. I can revisit it.

File: node/cli/src/cli.rs (hunk 1 above)
Comment (rlaferla) [reply node/cli/src/cli.rs:106]: It was decided to keep this default.

File: node/service/src/block_sealing.rs (hunk 2 above)
Comment (rlaferla) [reply node/service/src/block_sealing.rs]: Fixed

File: node/service/src/block_sealing.rs [hunk 3]
```diff
@@ -240,8 +242,9 @@ pub async fn run_seal_command<B, BI, CB, E, C, TP, SC, CS, CIDP, P>(
 	while let Some(command) = commands_stream.next().await {
 		match command {
 			EngineCommand::SealNewBlock { create_empty, finalize, parent_hash, sender } =>
-				if sealing_create_empty_blocks ||
-					(!sealing_create_empty_blocks && pool.ready().count() > 0)
+				if sealing_mode != SealingMode::Interval ||
+					sealing_create_empty_blocks ||
+					pool.ready().count() > 0
```
Comment (wilwade) [inline node/service/src/block_sealing.rs:247]: Just a comment to follow this logic:

- If we are in a mode *other* than instant sealing, form a block
- If we are in instant sealing AND we want to create empty blocks OR the count is > 0, form a block.

**Review by wilwade — APPROVED** [review]

File: node/service/src/block_sealing.rs (hunk 3 above)
Comment (rlaferla) [reply node/service/src/block_sealing.rs:247]: Almost.  I think you meant interval sealing.

File: .github/workflows/verify-pr-commit.yml [hunk 4]
```diff
@@ -648,7 +648,7 @@ jobs:
       - name: Run Integration Tests
         working-directory: integration-tests
         run: |
-          CHAIN_ENVIRONMENT="local" TEST_CHAIN_VALIDATION="instant_finality" WS_PROVIDER_URL="ws://127.0.0.1:9944" npm test
+          FUNDING_ACCOUNT_ENVIRONMENT="dev" TEST_CHAIN_VALIDATION="instant_finality" WS_PROVIDER_URL="ws://127.0.0.1:9944" npm test
```
[the remark this answers is not in the document]
Comment (rlaferla) [reply .github/workflows/verify-pr-commit.yml]: @johnmela will be making this change in a subsequent PR
