### PR TITLE
Automate Api Augment Updates

### LINKED ISSUE #382: [Chore] Improve and Automate js/api-augment Builds
Currently we have to keep up with updating the js/api-augment builds, I think we can automate them however now that we have instant sealing.

## Open Questions
- How do we feel about ignoring lock files?
- How does this get tested on PRs?
- Can we fail ci in a pr if we have missed a new rpc call?

## Idea
1. Remove all autogenerated files from js/api-augment
2. Remove and gitignore package-lock.json (and yarn lock) files and pin versions in package.json
3. Update the js build to trigger on any merge that changes on this directory or rust file
4. Build steps
    a. Run Frequency
    b. npm ci
    c. npm run fetch:local
    d. If no changes in metadata.json, exit
    e. npm run build
    f. trigger package release like it does now (main -> `@next`, release ->`@latest`)
5. Documentation in the readme about what happens.

### PR DESCRIPTION
**Pull request by wilwade**
# Goal
The goal of this PR is to stop having to remind people to update the JS api-augment and polluting PRs with generated code.

Closes #382

# Discussion
- Added a cli subcommand that exports the metadata
  - Is all of that really needed? I think so? The subcommands have a lot of options and I think I got it to a minimal set.
- Update the CI to handle exporting the metadata and then building the package.

# Checklist
- [x] N/A Chain spec updated
- [x] Updated the js/api-augment code if a custom RPC added/changed
- [ ] CI Docs updated? (TODO)
- [x] Tests added
- [x] N/A Benchmarks added
- [x] N/A Weights updated

### CODE REVIEW

File: node/cli/src/command.rs [hunk 1]
```diff
@@ -325,6 +325,29 @@ pub fn run() -> Result<()> {
...
+				{
+					// grab the task manager.
+					let registry =
+						&runner.config().prometheus_config.as_ref().map(|cfg| &cfg.registry);
+					let task_manager =
+						TaskManager::new(runner.config().tokio_handle.clone(), *registry)
+							.map_err(|e| format!("Error: {:?}", e))?;
+
+					runner.async_run(|config| {
+						let partials = service::new_partial::<RuntimeApi, Executor, _>(
```
Comment (saraswatpuneet) [inline node/cli/src/command.rs:341]: Registry and Task manager vars can be moved inside like partials

**Review by saraswatpuneet — APPROVED** [review]
:robot:

File: js/api-augment/definitions/index.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// Add a default export here for each definition
+// export { default as pallet } from "./pallet";
+
+export { default as msa } from "./msa";
+export { default as messages } from "./messages";
+export { default as schemas } from "./schemas";
```
Comment (saraswatpuneet) [inline js/api-augment/definitions/index.ts:6]: Will these be generated in interface folder?

Comment (saraswatpuneet) [reply js/api-augment/definitions/index.ts:6]: Aah i saw the export the other end , cool

**Review by saraswatpuneet — APPROVED** [review]
