### PR TITLE
fix: Added missing terminology descriptions

### LINKED ISSUE #1542: Update rust docs for Capacity
As you can see we forgot to add the Terminology for

- [x] Staker: [insert description].
- [x] Target [insert description].
- [x] Epoch Period: [insert description here].
- [x] Capacity: [insert description here].
- [x] Replenishable: [insert description here].

Notes:
https://libertydsnp.github.io/frequency/pallet_capacity/index.html

### PR DESCRIPTION
**Pull request by rlaferla**
# Goal
The goal of this PR is to add descriptions for Capacity terminology

Closes #1542

### CODE REVIEW

File: pallets/capacity/src/lib.rs [hunk 1]
```diff
@@ -31,11 +31,11 @@
...
-//! * **Staker:** [insert description].
-//! * **Target** [insert description].
-//! * **Epoch Period:** [insert description here].
-//! * **Capacity:** [insert description here].
-//! * **Replenishable:** [insert description here].
+//! * **Capacity:** A refillable and non-transferable resource that can be used to pay for transactions on the network.
+//! * **Staker:** An account that stakes tokens to the Frequency network in exchange for Capacity.
+//! * **Target** A provider MSA account that receives Capacity.
+//! * **Epoch Period:** The length of an epoch in blocks, used for replenishment and thawing.
+//! * **Replenishable:**  The ability of a MSA account to be refilled with Capacity after an epoch period.
```
Comment (wilwade) [inline pallets/capacity/src/lib.rs:38]:
```suggestion
//! * **Replenishable:**  The ability of a Provider MSA account to be refilled with Capacity after an epoch period.
```

**Review by enddynayn — APPROVED** [review]
💯 Nice!

**Review by shannonwells — APPROVED** [review]
Cool beans with awesome sauce
