### PR TITLE
Sync StorageVersion on existing pallets

### LINKED ISSUE #1826: Sync StorageVersion on existing pallets
# Description
After using and deploying some pallets on chain the `StorageVersion` got introduced and since they never got set correctly on some of them when we run `try-runtime` we see error like the following. 

```
2023-12-21 20:34:20 Finished post_upgrade
2023-12-21 20:34:20 Preimage: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).
2023-12-21 20:34:20 Democracy: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).
2023-12-21 20:34:20 Scheduler: On chain storage version StorageVersion(3) doesn't match current storage version StorageVersion(4).
2023-12-21 20:34:20 Balances: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).
2023-12-21 20:34:20 CollatorSelection: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).
2023-12-21 20:34:20 Multisig: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).
2023-12-21 20:34:20 Detected multiple errors while executing `try_on_runtime_upgrade`:
2023-12-21 20:34:20 Other("On chain and current storage version do not match. Missing runtime upgrade?")
[WW: 5 more of ^]
2023-12-21 20:34:20 panicked at 'called `Result::unwrap()` on an `Err` value: Other("Detected multiple errors while executing `try_on_runtime_upgrade`, check the logs!")', /Users/wilwade/dev/mrc/runtime/frequency/src/lib.rs:1330:65
```

## Acceptence criterea
- No try-runtime errors when ran against rococo test-net
- No try-runtime errors when ran against main-net

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is to fix errors related to StorageVersion when running try-runtime

Closes #1826 

# Discussion
- Running try-runtime against mainnet takes hours so instead used the following script which should have the same effect

`try-runtime --runtime ./target/release/wbuild/frequency-runtime/frequency_runtime.wasm on-runtime-upgrade  live --uri wss://1.rpc.frequency.xyz:443 --pallet  Capacity --pallet TimeRelease --pallet Balances --pallet System --pallet Messages --pallet Preimage --pallet Democracy --pallet Scheduler --pallet TransactionPayment --pallet Council --pallet TechnicalCommittee --pallet Treasury --pallet CollatorSelection --pallet Multisig --pallet FrequencyTxPayment --pallet Msa --pallet Messages --pallet ParachainSystem`

# Verification on rococo

```
[2023-12-22T18:43:34Z INFO  runtime::schemas] Migration Calculated weights=Weight { ref_time: 375000000, proof_size: 0 }
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_preimage
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_democracy
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_scheduler
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_balances
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_collator_selection
[2023-12-22T18:43:34Z INFO  frequency_runtime] Setting version on pallet_multisig
[2023-12-22T18:43:34Z INFO  try-runtime::cli] PoV size (zstd-compressed compact proof): 56.2 KB. For parachains, it's your responsibility to verify that a PoV of this size fits within any relaychain constraints.
[2023-12-22T18:43:34Z INFO  try-runtime::cli] Consumed ref_time: 0.3397s (67.94% of max 0.5s)
[2023-12-22T18:43:34Z INFO  try-runtime::cli] ✅ TryRuntime_on_runtime_upgrade executed without errors or weight safety warnings. Please note this does not guarantee a successful runtime upgrade. Always test your runtime upgrade with recent state, and ensure that the weight usage of your migrations will not drastically differ between testing and actual on-chain execution.
```

# Verification on mainnet

```
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_preimage
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_democracy
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_scheduler
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_balances
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_collator_selection
[2023-12-22T18:30:34Z INFO  frequency_runtime] Setting version on pallet_multisig
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for System
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for ParachainSystem
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Timestamp
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for ParachainInfo
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Preimage
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Democracy
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Scheduler
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Utility
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Balances
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for TransactionPayment
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Council
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for TechnicalCommittee
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Treasury
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Authorship
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for CollatorSelection
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Session
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Aura
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for AuraExt
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Multisig
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for TimeRelease
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Msa
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Messages
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Schemas
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for StatefulStorage
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Capacity
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for FrequencyTxPayment
[2023-12-22T18:30:34Z DEBUG runtime::frame-support] ✅ no migration for Handles
[2023-12-22T18:30:34Z DEBUG wasm-heap] allocator dropped: AllocationStats { bytes_allocated: 40, bytes_allocated_peak: 792, bytes_allocated_sum: 30048, address_space_used: 1392 }
[2023-12-22T18:30:34Z DEBUG try-runtime::cli] Proof: 0x00000000000000000000... / 37 nodes
[2023-12-22T18:30:34Z DEBUG try-runtime::cli] Encoded proof size: 5.1 KB
[2023-12-22T18:30:34Z DEBUG try-runtime::cli] Compact proof size: 4.0 KB
[2023-12-22T18:30:34Z INFO  try-runtime::cli] PoV size (zstd-compressed compact proof): 3.5 KB. For parachains, it's your responsibility to verify that a PoV of this size fits within any relaychain constraints.
[2023-12-22T18:30:34Z INFO  try-runtime::cli] Consumed ref_time: 0.00345s (0.69% of max 0.5s)
[2023-12-22T18:30:34Z INFO  try-runtime::cli] ✅ TryRuntime_on_runtime_upgrade executed without errors or weight safety warnings. Please note this does not guarantee a successful runtime upgrade. Always test your runtime upgrade with recent state, and ensure that the weight usage of your migrations will not drastically differ between testing and actual on-chain execution.
```

idempotent migrations also work based on latest checks added on try-runtime
```
[2023-12-26T19:34:02Z INFO  try_runtime_core::commands::on_runtime_upgrade] -------------------------------------------------------------------
    
    
[2023-12-26T19:34:02Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 Running TryRuntime_on_runtime_upgrade again to check idempotency: PreAndPost
    
    
[2023-12-26T19:34:02Z INFO  try_runtime_core::commands::on_runtime_upgrade] -------------------------------------------------------------------
[2023-12-26T19:34:02Z INFO  frequency_runtime] try-runtime::on_runtime_upgrade frequency.
[2023-12-26T19:34:02Z INFO  runtime::messages] Running pre_upgrade...
[2023-12-26T19:34:02Z INFO  runtime::messages] Running storage migration...
[2023-12-26T19:34:02Z INFO  runtime::messages] onchain_version= StorageVersion(2), current_version=StorageVersion(2)
[2023-12-26T19:34:02Z INFO  runtime::messages] Migration did not execute. This probably should be removed onchain:StorageVersion(2), current:StorageVersion(2)
[2023-12-26T19:34:02Z INFO  runtime::messages] Running post_upgrade...
[2023-12-26T19:34:02Z INFO  runtime::capacity] Old StorageAccountLedger migration attempted to run. Please remove
[2023-12-26T19:34:02Z INFO  runtime::capacity] Old Capacity Locks->Freezes migration attempted to run. Please remove
[2023-12-26T19:34:02Z INFO  runtime::schemas] Running pre_upgrade...
[2023-12-26T19:34:02Z INFO  runtime::schemas] Running storage migration...
[2023-12-26T19:34:02Z INFO  runtime::schemas] onchain_version= StorageVersion(3), current_version=StorageVersion(3)
[2023-12-26T19:34:02Z INFO  runtime::schemas] Migration did not execute. This probably should be removed onchain:StorageVersion(3), current:StorageVersion(3)
[2023-12-26T19:34:02Z INFO  runtime::schemas] Running post_upgrade...
[2023-12-26T19:34:02Z INFO  try-runtime::cli] PoV size (zstd-compressed compact proof): 3.5 KB. For parachains, it's your responsibility to verify that a PoV of this size fits within any relaychain constraints.
[2023-12-26T19:34:02Z INFO  try-runtime::cli] Consumed ref_time: 0.00345s (0.69% of max 0.5s)
[2023-12-26T19:34:02Z INFO  try-runtime::cli] ✅ No weight safety issues detected. Please note this does not guarantee a successful runtime upgrade. Always test your runtime upgrade with recent state, and ensure that the weight usage of your migrations will not drastically differ between testing and actual on-chain execution.
```

### CODE REVIEW

File: pallets/messages/src/migration/v2.rs [hunk 1]
```diff
@@ -79,19 +79,21 @@ impl<T: Config> OnRuntimeUpgrade for MigrateToV2<T> {
 	#[cfg(feature = "try-runtime")]
 	fn post_upgrade(state: Vec<u8>) -> Result<(), TryRuntimeError> {
 		log::info!(target: LOG_TARGET, "Running post_upgrade...");
+		let onchain_version = Pallet::<T>::on_chain_storage_version();
+		if onchain_version < 2 {
```
Comment (aramikm) [inline pallets/messages/src/migration/v2.rs:83]: since messages changes are not deployed on main-net yet had to add this check

File: runtime/frequency/src/lib.rs [hunk 2]
```diff
@@ -217,12 +218,79 @@ pub type Executive = frame_executive::Executive<
 	Runtime,
 	AllPalletsWithSystem,
 	(
+		pallet_messages::migration::v2::MigrateToV2<Runtime>,
 		pallet_capacity::migration::v2::MigrateToV2<Runtime>,
 		pallet_capacity::migration::v3::MigrationToV3<Runtime, pallet_balances::Pallet<Runtime>>,
 		pallet_schemas::migration::v3::MigrateToV3<Runtime>,
+		MigratePalletsCurrentStorage<Runtime>,
```
Comment (aramikm) [inline runtime/frequency/src/lib.rs:225]: Runs after all migrations and syncs the pallets that are not in sync

**Review by enddynayn — APPROVED** [review]
great! 👍

**Review by mattheworris — COMMENTED** [review]
Approved pending agreed updates for try-runtime idempotency.

**Review by saraswatpuneet — APPROVED** [review]

**Comment by aramikm** [comment]
@mattheworris Idempotency changes are applied

**Review by mattheworris — APPROVED** [review]
:shipit:
