### PR TITLE
fix type definition mismatch for schemas

### LINKED ISSUE #1393: Bug: Settings not working for getSchemaById RPC
Expected: `getBySchemaId` RPC settings either returns the bitwise or the array of set bits.

Actual: Returns an empty array

### RPC Call Rococo Schema 17
image

### State Call RPC Rococo Schema 17
image

### PR DESCRIPTION
**Pull request by saraswatpuneet**
# Goal
The goal of this PR is to fix a api bug for schemas causing rpc to send empty vec
Closes #1393 

# Checklist
- [ ] Chain spec updated
- [x] Custom RPC OR Runtime API added/changed? Updated js/api-augment.
- [ ] Design doc(s) updated
- [x] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

### CODE REVIEW

File: js/api-augment/definitions/schemas.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export default {
       model: "SchemaModel",
       model_type: "ModelType",
       payload_location: "PayloadLocation",
-      setting: "Vec<SchemaSetting>",
+      settings: "Vec<SchemaSetting>",
```
Comment (saraswatpuneet) [inline js/api-augment/definitions/schemas.ts:37]: this was the bug, rpc in node returns "settings" while api had "setting" causing fields mismatch

**Review by wilwade — APPROVED** [review]

**Review by JoeCap08055 — APPROVED** [review]
